In [1]:
import pandas as pd
import numpy as np

In [2]:
#create messy raw data
data = { "EmpId": [101, 102, "103", 104, 105, 106, 107, 108, 109, 110],
         "fullName": [
             " Alice Johnson ", "MICHEAL smith", "sarah lee", "David-Kim", None, "john brown", "Emma Wilson", "TOM davis", "Jane Miller", "Chris taylor"
         ], "Dept": ["IT", "hr", "Mktng", "IT", "Customer Care", "marketing", "Finance", None, "HR", "marketing"],
         "Age": [29, "thirty-five", 26, 31, 42, 27, 33, 30, None, 28],
         "Salary($)": ["$5500.50", "4800", "4200.75", "NaN", "6100", "4,300", "5800", "5000", "4700.0", "4400"], "JoinDate" : [ 
             "12-04-2021" , "2020.11.01" , "Jan 18, 2022" , "2019/9/25" , "07/05/18" , "2021-10-14" ,
             "2019/12/01" , "2020-03-22" , "May 10th, 2021" , "2022-02-05" ],
         "Performance": [87, "73", 90, 65, 82, 75, 88, None, "79%", "91"],
         "Remote?": ["Yes", "No", "Y", "N", "yes", "no", "Y", "Yes", None, "True"]
       }

In [3]:
#create a dataframe 
data_frame = pd.DataFrame(data)

#convert dataframe into csv file
data_frame.to_csv("data/employee_dataset.csv", index=False)

#load dataset
df = pd.read_csv("data/employee_dataset.csv")


df

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris taylor,marketing,28,4400,2022-02-05,91,True

In [4]:
#check the info of the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   EmpId        10 non-null     int64
 1   fullName     9 non-null      str
 2   Dept         9 non-null      str
 3   Age          9 non-null      str
 4   Salary($)    9 non-null      str
 5   JoinDate     10 non-null     str
 6   Performance  9 non-null      str
 7   Remote?      9 non-null      str
dtypes: int64(1), str(7)
memory usage: 772.0 bytes

In [5]:
#get the dataset shape
df.shape

(10, 8)

In [6]:
#get the first five rows
df.head()

,EmpId,fullName,Dept,Age,Salary($),JoinDate,Performance,Remote?
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes

In [7]:
#get the dataset colunms
df.columns

Index(['EmpId', 'fullName', 'Dept', 'Age', 'Salary($)', 'JoinDate',
       'Performance', 'Remote?'],
      dtype='str')

In [8]:
#check missing value
df.isnull().sum()

EmpId          0
fullName       1
Dept           1
Age            1
Salary($)      1
JoinDate       0
Performance    1
Remote?        1
dtype: int64

In [9]:
#inspect unique values in columns
print(df['Dept'].unique())
print(df['Age'].unique())
print(df['Remote?'].unique())

<StringArray>
['IT', 'hr', 'Mktng', 'Customer Care', 'marketing', 'Finance', nan, 'HR']
Length: 8, dtype: str
<StringArray>
['29', 'thirty-five', '26', '31', '42', '27', '33', '30', nan, '28']
Length: 10, dtype: str
<StringArray>
['Yes', 'No', 'Y', 'N', 'yes', 'no', nan, 'True']
Length: 8, dtype: str

In [10]:
#access salary value
df['Salary($)'].to_list()

['$5500.50',
 '4800',
 '4200.75',
 nan,
 '6100',
 '4,300',
 '5800',
 '5000',
 '4700.0',
 '4400']

In [11]:
df['fullName'].to_list()

[' Alice Johnson ',
 'MICHEAL smith',
 'sarah lee',
 'David-Kim',
 nan,
 'john brown',
 'Emma Wilson',
 'TOM davis',
 'Jane Miller',
 'Chris taylor']

In [12]:
df['Salary($)'].head()

0    $5500.50
1        4800
2     4200.75
3         NaN
4        6100
Name: Salary($), dtype: str

In [13]:
#start cleaning inconsistent values
#clean columns name
df.rename(columns={
    "Empid": "emp_id",
    "fullName": "full_name",
    "Dept": "department",
    "Age": "age",
    "Salary($)": "salary",
    "JoinDate": "join_date",
    "Performance": "performance",
    "Remote?": "remote"
}, inplace=True)
df

,EmpId,full_name,department,age,salary,join_date,performance,remote
0,101,Alice Johnson,IT,29,$5500.50,12-04-2021,87,Yes
1,102,MICHEAL smith,hr,thirty-five,4800,2020.11.01,73,No
2,103,sarah lee,Mktng,26,4200.75,"Jan 18, 2022",90,Y
3,104,David-Kim,IT,31,NaN,2019/9/25,65,N
4,105,NaN,Customer Care,42,6100,07/05/18,82,yes
5,106,john brown,marketing,27,"4,300",2021-10-14,75,no
6,107,Emma Wilson,Finance,33,5800,2019/12/01,88,Y
7,108,TOM davis,NaN,30,5000,2020-03-22,NaN,Yes
8,109,Jane Miller,HR,NaN,4700.0,"May 10th, 2021",79%,NaN
9,110,Chris taylor,marketing,28,4400,2022-02-05,91,True

In [14]:
#clean incosistence values on full_name
df['full_name'] = (
    df['full_name']
    .str.strip()
    .str.title()
    .str.replace(r"[\s-]+", " ", regex=True)
)
df['full_name'].to_list()

['Alice Johnson',
 'Micheal Smith',
 'Sarah Lee',
 'David Kim',
 nan,
 'John Brown',
 'Emma Wilson',
 'Tom Davis',
 'Jane Miller',
 'Chris Taylor']

In [15]:
#clean incosistence values as department
df.replace({
    "hr": "HR",
    "Mktng": "Marketing",
    "marketing": "Marketing",
    None : np.nan
}, inplace=True)
df['department'].to_list()

['IT',
 'HR',
 'Marketing',
 'IT',
 'Customer Care',
 'Marketing',
 'Finance',
 nan,
 'HR',
 'Marketing']

In [16]:
#clean incosistency values in age
def clean_age(value):
    if value =="thirty-five":
        return 35
    elif isinstance(value, (int, float)):
        return value
    elif isinstance(value, str) and value.isdigit():
        return int(value)
    else:
        return np.nan
df['age'] = df['age'].apply(clean_age)

df['age']

0    29.0
1    35.0
2    26.0
3    31.0
4    42.0
5    27.0
6    33.0
7    30.0
8     NaN
9    28.0
Name: age, dtype: float64

In [19]:
# clean incosistency values on Salary
df['salary'] = (
    df['salary']
    .str.strip()
    .str.replace(r"[\s$]+", " ", regex=True
)
df['salary'].to_list()

['5500.50',
 '4800',
 '4200.75',
 nan,
 '6100',
 '4,300',
 '5800',
 '5000',
 '4700.0',
 '4400']

In [21]:
#clean incosistency values on performance
df['performance'] = (
    df['performance']
    .str.replace(r"[\s%]+", " ", regex=True)
)
df['performance']

0     87
1     73
2     90
3     65
4     82
5     75
6     88
7    NaN
8    79
9     91
Name: performance, dtype: str

In [26]:
#clean incosistency values on remote
df.replace({
    "Y": "Yes",
    "N": "No",
    "yes": "Yes",
    "no": "No",
    None : np.nan
}, inplace=True)

df['remote']

0     Yes
1      No
2     Yes
3      No
4     Yes
5      No
6     Yes
7     Yes
8     NaN
9    True
Name: remote, dtype: str