In [110]:
import pandas as pd
import numpy as np
from dateutil import parser

Part 1: Create a Messy Dataset

In [111]:
# Creating messy dataset
data = {
    "Product_ID": [
        "P001", "P002", "P003", "P004", "P005",
        "P006", "P007", "P008", "P009", "P010",
        "P011", "P012", "P013", "P014", "P015",
        "P016", "P017", "P018", "P002", "P020"
    ],

    "Product_Name": [
        "Laptop", "mouse", "KEYBOARD", "NaN", "Monitor",
        "Printer", "Laptop", "Webcam", "Speaker", "Router",
        "tablet", "Phone", "Charger", "Headset", "SSD",
        "Hard Drive", "USB Cable", "Mouse", "mouse", "Projector"
    ],

    "Category": [
        "Electronics", "electronics", "ELECTRONICS", "Accessories", "Electronics",
        "electronics", "Electronics", "Accessories", "ACCESSORIES", "Networking",
        "electronics", "Electronics", "Accessories", "electronics", "Storage",
        "STORAGE", "Accessories", "electronics", "electronics", "Electronics"
    ],

    "Supplier": [
        "TechCorp", "tech corp", "SupplyHub", "Supply Hub", "TechCorp",
        "MegaStore", "Techcorp", "SupplyHub", "Mega Store", "NetWorld",
        "TechCorp", "Tech Corp", "SupplyHub", "MegaStore", "StoragePlus",
        "Storage Plus", "SupplyHub", "tech corp", "tech corp", "VisionTech"
    ],

    "Quantity": [
        10, 25, "twenty", -5, 15,
        np.nan, 8, 12, 50, 20,
        30, -10, 18, 25, 5,
        40, 60, 22, 25, 7
    ],

    "Unit_Price": [
        850, 20, 45, 15, 300,
        1500, -999, "NaN", 75, 120,
        450, 100000, 12, 65, 80,
        95, 10, 25, 20, -50
    ],

    "Reorder_Level": [
        5, 10, 8, 5, 7,
        6, 5, 4, 15, 10,
        12, 8, 5, 7, 4,
        10, 15, 10, 10, 3
    ],

    "Last_Update": [
        "2025-01-10", "01/15/2025", "2025/02/10", "March 5 2025", "",
        "2025-13-01", "2025-04-11", "11-05-2025", "NaN", "2025/06/01",
        "2025-07-20", "07/25/2025", "2025.08.15", "2025-09-01", "invalid",
        "2025/10/10", "2025-11-11", "01/15/2025", "12/12/2025", ""
    ]
}

Part 2: Load and Inspect the Dataset

In [112]:
#create a dataframe 
data_frame = pd.DataFrame(data)

#convert dataframe into csv file
data_frame.to_csv("data/inventory_analysis.csv", index=False)

#load dataset
df = pd.read_csv("data/inventory_analysis.csv")


df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechCorp,10,850.0,5,2025-01-10
1,P002,mouse,electronics,tech corp,25,20.0,10,01/15/2025
2,P003,KEYBOARD,ELECTRONICS,SupplyHub,twenty,45.0,8,2025/02/10
3,P004,NaN,Accessories,Supply Hub,-5,15.0,5,March 5 2025
4,P005,Monitor,Electronics,TechCorp,15,300.0,7,NaN
5,P006,Printer,electronics,MegaStore,NaN,1500.0,6,2025-13-01
6,P007,Laptop,Electronics,Techcorp,8,-999.0,5,2025-04-11
7,P008,Webcam,Accessories,SupplyHub,12,NaN,4,11-05-2025
8,P009,Speaker,ACCESSORIES,Mega Store,50,75.0,15,NaN
9,P010,Router,Networking,NetWorld,20,120.0,10,2025/06/01
10,P011,tablet,electronics,TechCorp,30,450.0,12,2025-07-20
11,P012,Phone,Electronics,Tech Corp,-10,100000.0,8,07/25/2025
12,P013,Charger,Accessories,SupplyHub,18,12.0,5,2025.08.15
13,P014,Headset,electronics,MegaStore,25,65.0,7,2025-09-01
14,P015,SSD,Storage,StoragePlus,5,80.0,4,invalid
15,P016,Hard Drive,STORAGE,Storage Plus,40,95.0,10,2025/10/10
16,P017,USB Cable,Accessories,SupplyHub,60,10.0,15,2025-11-11
17,P018,Mouse,electronics,tech corp,22,25.0,10,01/15/2025
18,P002,mouse,electronics,tech corp,25,20.0,10,12/12/2025
19,P020,Projector,Electronics,VisionTech,7,-50.0,3,NaN

In [113]:
#Display the first and last 5 rows.
df.head()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechCorp,10,850.0,5,2025-01-10
1,P002,mouse,electronics,tech corp,25,20.0,10,01/15/2025
2,P003,KEYBOARD,ELECTRONICS,SupplyHub,twenty,45.0,8,2025/02/10
3,P004,NaN,Accessories,Supply Hub,-5,15.0,5,March 5 2025
4,P005,Monitor,Electronics,TechCorp,15,300.0,7,NaN

In [114]:
#Display the last 5 rows
df.tail()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
15,P016,Hard Drive,STORAGE,Storage Plus,40,95.0,10,2025/10/10
16,P017,USB Cable,Accessories,SupplyHub,60,10.0,15,2025-11-11
17,P018,Mouse,electronics,tech corp,22,25.0,10,01/15/2025
18,P002,mouse,electronics,tech corp,25,20.0,10,12/12/2025
19,P020,Projector,Electronics,VisionTech,7,-50.0,3,NaN

In [115]:
#Show basic information about the dataset using .info() and .describe().
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Product_ID     20 non-null     str
 1   Product_Name   19 non-null     str
 2   Category       20 non-null     str
 3   Supplier       20 non-null     str
 4   Quantity       19 non-null     str
 5   Unit_Price     19 non-null     float64
 6   Reorder_Level  20 non-null     int64
 7   Last_Update    17 non-null     str
dtypes: float64(1), int64(1), str(6)
memory usage: 1.4 KB

In [116]:
#Show basic information about the dataset using .describe().
df.describe().all()
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechCorp,10,850.0,5,2025-01-10
1,P002,mouse,electronics,tech corp,25,20.0,10,01/15/2025
2,P003,KEYBOARD,ELECTRONICS,SupplyHub,twenty,45.0,8,2025/02/10
3,P004,NaN,Accessories,Supply Hub,-5,15.0,5,March 5 2025
4,P005,Monitor,Electronics,TechCorp,15,300.0,7,NaN
5,P006,Printer,electronics,MegaStore,NaN,1500.0,6,2025-13-01
6,P007,Laptop,Electronics,Techcorp,8,-999.0,5,2025-04-11
7,P008,Webcam,Accessories,SupplyHub,12,NaN,4,11-05-2025
8,P009,Speaker,ACCESSORIES,Mega Store,50,75.0,15,NaN
9,P010,Router,Networking,NetWorld,20,120.0,10,2025/06/01
10,P011,tablet,electronics,TechCorp,30,450.0,12,2025-07-20
11,P012,Phone,Electronics,Tech Corp,-10,100000.0,8,07/25/2025
12,P013,Charger,Accessories,SupplyHub,18,12.0,5,2025.08.15
13,P014,Headset,electronics,MegaStore,25,65.0,7,2025-09-01
14,P015,SSD,Storage,StoragePlus,5,80.0,4,invalid
15,P016,Hard Drive,STORAGE,Storage Plus,40,95.0,10,2025/10/10
16,P017,USB Cable,Accessories,SupplyHub,60,10.0,15,2025-11-11
17,P018,Mouse,electronics,tech corp,22,25.0,10,01/15/2025
18,P002,mouse,electronics,tech corp,25,20.0,10,12/12/2025
19,P020,Projector,Electronics,VisionTech,7,-50.0,3,NaN

In [117]:
#Identify missing values and duplicated rows.
print("Missing Values")
df.isnull().sum()

Missing Values

Product_ID       0
Product_Name     1
Category         0
Supplier         0
Quantity         1
Unit_Price       1
Reorder_Level    0
Last_Update      3
dtype: int64

In [133]:
#Identify duplicate rows
df[df.duplicated(keep=False)]

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
1,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
18,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT

PART 3. Clean the Data

In [119]:
#Handle missing values: decide whether to fill or drop them.
df["Product_Name"] = df["Product_Name"].fillna("Unknown")
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,TechCorp,10,850.0,5,2025-01-10
1,P002,mouse,electronics,tech corp,25,20.0,10,01/15/2025
2,P003,KEYBOARD,ELECTRONICS,SupplyHub,twenty,45.0,8,2025/02/10
3,P004,Unknown,Accessories,Supply Hub,-5,15.0,5,March 5 2025
4,P005,Monitor,Electronics,TechCorp,15,300.0,7,NaN
5,P006,Printer,electronics,MegaStore,NaN,1500.0,6,2025-13-01
6,P007,Laptop,Electronics,Techcorp,8,-999.0,5,2025-04-11
7,P008,Webcam,Accessories,SupplyHub,12,NaN,4,11-05-2025
8,P009,Speaker,ACCESSORIES,Mega Store,50,75.0,15,NaN
9,P010,Router,Networking,NetWorld,20,120.0,10,2025/06/01
10,P011,tablet,electronics,TechCorp,30,450.0,12,2025-07-20
11,P012,Phone,Electronics,Tech Corp,-10,100000.0,8,07/25/2025
12,P013,Charger,Accessories,SupplyHub,18,12.0,5,2025.08.15
13,P014,Headset,electronics,MegaStore,25,65.0,7,2025-09-01
14,P015,SSD,Storage,StoragePlus,5,80.0,4,invalid
15,P016,Hard Drive,STORAGE,Storage Plus,40,95.0,10,2025/10/10
16,P017,USB Cable,Accessories,SupplyHub,60,10.0,15,2025-11-11
17,P018,Mouse,electronics,tech corp,22,25.0,10,01/15/2025
18,P002,mouse,electronics,tech corp,25,20.0,10,12/12/2025
19,P020,Projector,Electronics,VisionTech,7,-50.0,3,NaN

In [134]:
#Remove duplicate rows.
df.drop_duplicates()

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techcorp,10.0,850.0,5,2025-01-10
1,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
2,P003,Keyboard,Electronics,Supplyhub,21.0,45.0,8,NaT
3,P004,Unknown,Accessories,Supply Hub,21.0,15.0,5,NaT
4,P005,Monitor,Electronics,Techcorp,15.0,300.0,7,NaT
5,P006,Printer,Electronics,Megastore,21.0,1500.0,6,NaT
6,P007,Laptop,Electronics,Techcorp,8.0,75.0,5,2025-04-11
7,P008,Webcam,Accessories,Supplyhub,12.0,75.0,4,NaT
8,P009,Speaker,Accessories,Mega Store,50.0,75.0,15,NaT
9,P010,Router,Networking,Networld,20.0,120.0,10,NaT
10,P011,Tablet,Electronics,Techcorp,30.0,450.0,12,2025-07-20
11,P012,Phone,Electronics,Tech Corp,21.0,100000.0,8,NaT
12,P013,Charger,Accessories,Supplyhub,18.0,12.0,5,NaT
13,P014,Headset,Electronics,Megastore,25.0,65.0,7,2025-09-01
14,P015,Ssd,Storage,Storageplus,5.0,80.0,4,NaT
15,P016,Hard Drive,Storage,Storage Plus,40.0,95.0,10,NaT
16,P017,Usb Cable,Accessories,Supplyhub,60.0,10.0,15,2025-11-11
17,P018,Mouse,Electronics,Tech Corp,22.0,25.0,10,NaT
19,P020,Projector,Electronics,Visiontech,7.0,75.0,3,NaT

In [121]:
#Standardize text: make all Product_Name, Category, and Supplier lowercase (or title case).
df["Product_Name"] = df["Product_Name"].str.title()
df["Category"] = df["Category"].str.title()
df["Supplier"] = df["Supplier"].str.title()
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techcorp,10,850.0,5,2025-01-10
1,P002,Mouse,Electronics,Tech Corp,25,20.0,10,01/15/2025
2,P003,Keyboard,Electronics,Supplyhub,twenty,45.0,8,2025/02/10
3,P004,Unknown,Accessories,Supply Hub,-5,15.0,5,March 5 2025
4,P005,Monitor,Electronics,Techcorp,15,300.0,7,NaN
5,P006,Printer,Electronics,Megastore,NaN,1500.0,6,2025-13-01
6,P007,Laptop,Electronics,Techcorp,8,-999.0,5,2025-04-11
7,P008,Webcam,Accessories,Supplyhub,12,NaN,4,11-05-2025
8,P009,Speaker,Accessories,Mega Store,50,75.0,15,NaN
9,P010,Router,Networking,Networld,20,120.0,10,2025/06/01
10,P011,Tablet,Electronics,Techcorp,30,450.0,12,2025-07-20
11,P012,Phone,Electronics,Tech Corp,-10,100000.0,8,07/25/2025
12,P013,Charger,Accessories,Supplyhub,18,12.0,5,2025.08.15
13,P014,Headset,Electronics,Megastore,25,65.0,7,2025-09-01
14,P015,Ssd,Storage,Storageplus,5,80.0,4,invalid
15,P016,Hard Drive,Storage,Storage Plus,40,95.0,10,2025/10/10
16,P017,Usb Cable,Accessories,Supplyhub,60,10.0,15,2025-11-11
17,P018,Mouse,Electronics,Tech Corp,22,25.0,10,01/15/2025
18,P002,Mouse,Electronics,Tech Corp,25,20.0,10,12/12/2025
19,P020,Projector,Electronics,Visiontech,7,-50.0,3,NaN

In [122]:
#Fix data types: convert columns to proper numeric or datetime types.
# Convert numeric columns
df["Quantity"] = pd.to_numeric(df["Quantity"], errors='coerce')
df["Unit_Price"] = pd.to_numeric(df["Unit_Price"], errors='coerce')
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techcorp,10.0,850.0,5,2025-01-10
1,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,01/15/2025
2,P003,Keyboard,Electronics,Supplyhub,NaN,45.0,8,2025/02/10
3,P004,Unknown,Accessories,Supply Hub,-5.0,15.0,5,March 5 2025
4,P005,Monitor,Electronics,Techcorp,15.0,300.0,7,NaN
5,P006,Printer,Electronics,Megastore,NaN,1500.0,6,2025-13-01
6,P007,Laptop,Electronics,Techcorp,8.0,-999.0,5,2025-04-11
7,P008,Webcam,Accessories,Supplyhub,12.0,NaN,4,11-05-2025
8,P009,Speaker,Accessories,Mega Store,50.0,75.0,15,NaN
9,P010,Router,Networking,Networld,20.0,120.0,10,2025/06/01
10,P011,Tablet,Electronics,Techcorp,30.0,450.0,12,2025-07-20
11,P012,Phone,Electronics,Tech Corp,-10.0,100000.0,8,07/25/2025
12,P013,Charger,Accessories,Supplyhub,18.0,12.0,5,2025.08.15
13,P014,Headset,Electronics,Megastore,25.0,65.0,7,2025-09-01
14,P015,Ssd,Storage,Storageplus,5.0,80.0,4,invalid
15,P016,Hard Drive,Storage,Storage Plus,40.0,95.0,10,2025/10/10
16,P017,Usb Cable,Accessories,Supplyhub,60.0,10.0,15,2025-11-11
17,P018,Mouse,Electronics,Tech Corp,22.0,25.0,10,01/15/2025
18,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,12/12/2025
19,P020,Projector,Electronics,Visiontech,7.0,-50.0,3,NaN

In [123]:
# Convert dates
df["Last_Update"] = pd.to_datetime(df["Last_Update"], errors='coerce')
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techcorp,10.0,850.0,5,2025-01-10
1,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
2,P003,Keyboard,Electronics,Supplyhub,NaN,45.0,8,NaT
3,P004,Unknown,Accessories,Supply Hub,-5.0,15.0,5,NaT
4,P005,Monitor,Electronics,Techcorp,15.0,300.0,7,NaT
5,P006,Printer,Electronics,Megastore,NaN,1500.0,6,NaT
6,P007,Laptop,Electronics,Techcorp,8.0,-999.0,5,2025-04-11
7,P008,Webcam,Accessories,Supplyhub,12.0,NaN,4,NaT
8,P009,Speaker,Accessories,Mega Store,50.0,75.0,15,NaT
9,P010,Router,Networking,Networld,20.0,120.0,10,NaT
10,P011,Tablet,Electronics,Techcorp,30.0,450.0,12,2025-07-20
11,P012,Phone,Electronics,Tech Corp,-10.0,100000.0,8,NaT
12,P013,Charger,Accessories,Supplyhub,18.0,12.0,5,NaT
13,P014,Headset,Electronics,Megastore,25.0,65.0,7,2025-09-01
14,P015,Ssd,Storage,Storageplus,5.0,80.0,4,NaT
15,P016,Hard Drive,Storage,Storage Plus,40.0,95.0,10,NaT
16,P017,Usb Cable,Accessories,Supplyhub,60.0,10.0,15,2025-11-11
17,P018,Mouse,Electronics,Tech Corp,22.0,25.0,10,NaT
18,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
19,P020,Projector,Electronics,Visiontech,7.0,-50.0,3,NaT

In [124]:
#Handle incorrect values:
#Replace or drop rows with negative or unrealistic prices/quantities.
df.loc[df["Quantity"] < 0, "Quantity"] = np.nan
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techcorp,10.0,850.0,5,2025-01-10
1,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
2,P003,Keyboard,Electronics,Supplyhub,NaN,45.0,8,NaT
3,P004,Unknown,Accessories,Supply Hub,NaN,15.0,5,NaT
4,P005,Monitor,Electronics,Techcorp,15.0,300.0,7,NaT
5,P006,Printer,Electronics,Megastore,NaN,1500.0,6,NaT
6,P007,Laptop,Electronics,Techcorp,8.0,-999.0,5,2025-04-11
7,P008,Webcam,Accessories,Supplyhub,12.0,NaN,4,NaT
8,P009,Speaker,Accessories,Mega Store,50.0,75.0,15,NaT
9,P010,Router,Networking,Networld,20.0,120.0,10,NaT
10,P011,Tablet,Electronics,Techcorp,30.0,450.0,12,2025-07-20
11,P012,Phone,Electronics,Tech Corp,NaN,100000.0,8,NaT
12,P013,Charger,Accessories,Supplyhub,18.0,12.0,5,NaT
13,P014,Headset,Electronics,Megastore,25.0,65.0,7,2025-09-01
14,P015,Ssd,Storage,Storageplus,5.0,80.0,4,NaT
15,P016,Hard Drive,Storage,Storage Plus,40.0,95.0,10,NaT
16,P017,Usb Cable,Accessories,Supplyhub,60.0,10.0,15,2025-11-11
17,P018,Mouse,Electronics,Tech Corp,22.0,25.0,10,NaT
18,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
19,P020,Projector,Electronics,Visiontech,7.0,-50.0,3,NaT

In [125]:
# Remove negative prices
df.loc[df["Unit_Price"] < 0, "Unit_Price"] = np.nan
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techcorp,10.0,850.0,5,2025-01-10
1,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
2,P003,Keyboard,Electronics,Supplyhub,NaN,45.0,8,NaT
3,P004,Unknown,Accessories,Supply Hub,NaN,15.0,5,NaT
4,P005,Monitor,Electronics,Techcorp,15.0,300.0,7,NaT
5,P006,Printer,Electronics,Megastore,NaN,1500.0,6,NaT
6,P007,Laptop,Electronics,Techcorp,8.0,NaN,5,2025-04-11
7,P008,Webcam,Accessories,Supplyhub,12.0,NaN,4,NaT
8,P009,Speaker,Accessories,Mega Store,50.0,75.0,15,NaT
9,P010,Router,Networking,Networld,20.0,120.0,10,NaT
10,P011,Tablet,Electronics,Techcorp,30.0,450.0,12,2025-07-20
11,P012,Phone,Electronics,Tech Corp,NaN,100000.0,8,NaT
12,P013,Charger,Accessories,Supplyhub,18.0,12.0,5,NaT
13,P014,Headset,Electronics,Megastore,25.0,65.0,7,2025-09-01
14,P015,Ssd,Storage,Storageplus,5.0,80.0,4,NaT
15,P016,Hard Drive,Storage,Storage Plus,40.0,95.0,10,NaT
16,P017,Usb Cable,Accessories,Supplyhub,60.0,10.0,15,2025-11-11
17,P018,Mouse,Electronics,Tech Corp,22.0,25.0,10,NaT
18,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
19,P020,Projector,Electronics,Visiontech,7.0,NaN,3,NaT

In [126]:
# Fill remaining NaN values
df["Quantity"] = df["Quantity"].fillna(df["Quantity"].median())
df["Unit_Price"] = df["Unit_Price"].fillna(df["Unit_Price"].median())
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techcorp,10.0,850.0,5,2025-01-10
1,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
2,P003,Keyboard,Electronics,Supplyhub,21.0,45.0,8,NaT
3,P004,Unknown,Accessories,Supply Hub,21.0,15.0,5,NaT
4,P005,Monitor,Electronics,Techcorp,15.0,300.0,7,NaT
5,P006,Printer,Electronics,Megastore,21.0,1500.0,6,NaT
6,P007,Laptop,Electronics,Techcorp,8.0,75.0,5,2025-04-11
7,P008,Webcam,Accessories,Supplyhub,12.0,75.0,4,NaT
8,P009,Speaker,Accessories,Mega Store,50.0,75.0,15,NaT
9,P010,Router,Networking,Networld,20.0,120.0,10,NaT
10,P011,Tablet,Electronics,Techcorp,30.0,450.0,12,2025-07-20
11,P012,Phone,Electronics,Tech Corp,21.0,100000.0,8,NaT
12,P013,Charger,Accessories,Supplyhub,18.0,12.0,5,NaT
13,P014,Headset,Electronics,Megastore,25.0,65.0,7,2025-09-01
14,P015,Ssd,Storage,Storageplus,5.0,80.0,4,NaT
15,P016,Hard Drive,Storage,Storage Plus,40.0,95.0,10,NaT
16,P017,Usb Cable,Accessories,Supplyhub,60.0,10.0,15,2025-11-11
17,P018,Mouse,Electronics,Tech Corp,22.0,25.0,10,NaT
18,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
19,P020,Projector,Electronics,Visiontech,7.0,75.0,3,NaT

In [127]:
#Standardize date formats in Last_Updated.
df["Last_Update"] = pd.to_datetime(df["Last_Update"], errors='coerce')
df

,Product_ID,Product_Name,Category,Supplier,Quantity,Unit_Price,Reorder_Level,Last_Update
0,P001,Laptop,Electronics,Techcorp,10.0,850.0,5,2025-01-10
1,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
2,P003,Keyboard,Electronics,Supplyhub,21.0,45.0,8,NaT
3,P004,Unknown,Accessories,Supply Hub,21.0,15.0,5,NaT
4,P005,Monitor,Electronics,Techcorp,15.0,300.0,7,NaT
5,P006,Printer,Electronics,Megastore,21.0,1500.0,6,NaT
6,P007,Laptop,Electronics,Techcorp,8.0,75.0,5,2025-04-11
7,P008,Webcam,Accessories,Supplyhub,12.0,75.0,4,NaT
8,P009,Speaker,Accessories,Mega Store,50.0,75.0,15,NaT
9,P010,Router,Networking,Networld,20.0,120.0,10,NaT
10,P011,Tablet,Electronics,Techcorp,30.0,450.0,12,2025-07-20
11,P012,Phone,Electronics,Tech Corp,21.0,100000.0,8,NaT
12,P013,Charger,Accessories,Supplyhub,18.0,12.0,5,NaT
13,P014,Headset,Electronics,Megastore,25.0,65.0,7,2025-09-01
14,P015,Ssd,Storage,Storageplus,5.0,80.0,4,NaT
15,P016,Hard Drive,Storage,Storage Plus,40.0,95.0,10,NaT
16,P017,Usb Cable,Accessories,Supplyhub,60.0,10.0,15,2025-11-11
17,P018,Mouse,Electronics,Tech Corp,22.0,25.0,10,NaT
18,P002,Mouse,Electronics,Tech Corp,25.0,20.0,10,NaT
19,P020,Projector,Electronics,Visiontech,7.0,75.0,3,NaT

Part 4: Analyze and Sort the Data

In [128]:
#Which products need restocking (where Quantity < Reorder_Level)?
restock = df[df["Quantity"] < df["Reorder_Level"]]

print("Products That Need Restocking")
print(restock[["Product_Name", "Quantity", "Reorder_Level"]])

Products That Need Restocking
Empty DataFrame
Columns: [Product_Name, Quantity, Reorder_Level]
Index: []

In [129]:
#What is the average unit price per category?
avg_price = df.groupby("Category")["Unit_Price"].mean()

print("Average Unit Price Per Category")
print(avg_price)

Average Unit Price Per Category
Category
Accessories      37.40
Electronics    8618.75
Networking      120.00
Storage          87.50
Name: Unit_Price, dtype: float64

In [1]:
#Which supplier provides the most products?
supplier_count = df["Supplier"].value_counts()

print("Supplier Product Count")
print(supplier_count)



print(f"\nSupplier with most products: {top_supplier}")

NameError: name 'df' is not defined

In [131]:
#List the top 5 most expensive products.
top_expensive = df.nlargest(5, "Unit_Price")

print("Top 5 Most Expensive Products")
print(top_expensive[["Product_Name", "Unit_Price"]])

Top 5 Most Expensive Products
   Product_Name  Unit_Price
11        Phone    100000.0
5       Printer      1500.0
0        Laptop       850.0
10       Tablet       450.0
4       Monitor       300.0

In [132]:
#Sort the cleaned dataset by Category and then by Unit_Price in descending order.
sorted_df = df.sort_values( by=["Category", "Unit_Price"],ascending=[True, False])
print(sorted_df)

   Product_ID Product_Name     Category      Supplier  Quantity  Unit_Price  \
7        P008       Webcam  Accessories     Supplyhub      12.0        75.0
8        P009      Speaker  Accessories    Mega Store      50.0        75.0
3        P004      Unknown  Accessories    Supply Hub      21.0        15.0
12       P013      Charger  Accessories     Supplyhub      18.0        12.0
16       P017    Usb Cable  Accessories     Supplyhub      60.0        10.0
11       P012        Phone  Electronics     Tech Corp      21.0    100000.0
5        P006      Printer  Electronics     Megastore      21.0      1500.0
0        P001       Laptop  Electronics      Techcorp      10.0       850.0
10       P011       Tablet  Electronics      Techcorp      30.0       450.0
4        P005      Monitor  Electronics      Techcorp      15.0       300.0
6        P007       Laptop  Electronics      Techcorp       8.0        75.0
19       P020    Projector  Electronics    Visiontech       7.0        75.0
13       P014      Headset  Electronics     Megastore      25.0        65.0
2        P003     Keyboard  Electronics     Supplyhub      21.0        45.0
17       P018        Mouse  Electronics     Tech Corp      22.0        25.0
1        P002        Mouse  Electronics     Tech Corp      25.0        20.0
18       P002        Mouse  Electronics     Tech Corp      25.0        20.0
9        P010       Router   Networking      Networld      20.0       120.0
15       P016   Hard Drive      Storage  Storage Plus      40.0        95.0
14       P015          Ssd      Storage   Storageplus       5.0        80.0

    Reorder_Level Last_Update
7               4         NaT
8              15         NaT
3               5         NaT
12              5         NaT
16             15  2025-11-11
11              8         NaT
5               6         NaT
0               5  2025-01-10
10             12  2025-07-20
4               7         NaT
6               5  2025-04-11
19              3         NaT
13              7  2025-09-01
2               8         NaT
17             10         NaT
1              10         NaT
18             10         NaT
9              10         NaT
15             10         NaT
14              4         NaT